{% set name = "lcensemble" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lcensemble-{{ version }}.tar.gz
  sha256: f5ef51fe1d10dc1581d041fb5c9b818e7c4aac043224b926961902d48845b236

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - hyperopt ==0.2.7
    - numpy ==1.21.5
    - pandas ==1.3.5
    - python >=3.7
    - scikit-learn ==1.0.2
    - xgboost ==1.5.0

test:
  imports:
    - lce

about:
  home: https://lce.readthedocs.io/en/latest/
  summary: Local Cascade Ensemble package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LocalCascadeEnsemble
