{% set name = "lcensemble" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lcensemble-{{ version }}.tar.gz
  sha256: 873bd8bef8782976fc7b239365346a036630cef7311083dd21da8b7cfd46bf32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - hyperopt >=0.2.7
    - matplotlib-base
    - numpy >=1.19.2
    - pandas ==1.3.5
    - python >=3.7
    - scikit-learn >=1.0.0
    - xgboost ==1.5.0

test:
  imports:
    - lce

about:
  home: https://pypi.org/project/lcensemble/
  doc_url: https://lce.readthedocs.io/en/latest/
  dev_url: https://github.com/LocalCascadeEnsemble/LCE
  summary: Local Cascade Ensemble package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - LocalCascadeEnsemble
